sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
node_js:
  - 8.12.0
branches:
  only:
    - master
script:
  - yarn test
  - yarn lint
  - yarn build
after_success:
  - yarn travis-deploy-once "yarn semantic-release"
